version: '3.9'

services:
    postgres:
        image: postgres:15
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 5s
            timeout: 5s
            retries: 10

    make-data-service:
        build:
            context: .
            dockerfile: make-data-service/Dockerfile
        ports:
            - "8002:8002"
        environment:
            ALPHA_API: ${ALPHA_API}
            ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}

    auth:
        build: ./auth-service
        ports:
            - "8001:8001"
        environment:
            JWT_SECRET: ${JWT_SECRET}
            DB_HOST: postgres
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            DB_NAME: ${POSTGRES_DB}
            ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
        depends_on:
            postgres:
                condition: service_healthy
        restart: unless-stopped

    portfolio:
        build:
            context: .
            dockerfile: portfolio-service/Dockerfile
        ports:
            - "8003:8003"
        environment:
            DB_HOST: postgres
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            DB_NAME: ${POSTGRES_DB}
            AUTH_SERVICE_URL: http://auth:8001
            MARKET_SERVICE_URL: http://make-data-service:8002
            ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
        depends_on:
            postgres:
                condition: service_healthy
            auth:
                condition: service_started