// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: market.proto

package market

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStockPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockPriceRequest) Reset() {
	*x = GetStockPriceRequest{}
	mi := &file_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockPriceRequest) ProtoMessage() {}

func (x *GetStockPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockPriceRequest.ProtoReflect.Descriptor instead.
func (*GetStockPriceRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{0}
}

func (x *GetStockPriceRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetStockPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CurrentPrice  float64                `protobuf:"fixed64,3,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	ChangePercent float64                `protobuf:"fixed64,4,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockPriceResponse) Reset() {
	*x = GetStockPriceResponse{}
	mi := &file_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockPriceResponse) ProtoMessage() {}

func (x *GetStockPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockPriceResponse.ProtoReflect.Descriptor instead.
func (*GetStockPriceResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{1}
}

func (x *GetStockPriceResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetStockPriceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetStockPriceResponse) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *GetStockPriceResponse) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *GetStockPriceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetStockPriceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetMultipleStocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"` // "repeated" = array/slice
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipleStocksRequest) Reset() {
	*x = GetMultipleStocksRequest{}
	mi := &file_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipleStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipleStocksRequest) ProtoMessage() {}

func (x *GetMultipleStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipleStocksRequest.ProtoReflect.Descriptor instead.
func (*GetMultipleStocksRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{2}
}

func (x *GetMultipleStocksRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type GetMultipleStocksResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Stocks        []*GetStockPriceResponse `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	Success       bool                     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                   `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipleStocksResponse) Reset() {
	*x = GetMultipleStocksResponse{}
	mi := &file_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipleStocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipleStocksResponse) ProtoMessage() {}

func (x *GetMultipleStocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipleStocksResponse.ProtoReflect.Descriptor instead.
func (*GetMultipleStocksResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{3}
}

func (x *GetMultipleStocksResponse) GetStocks() []*GetStockPriceResponse {
	if x != nil {
		return x.Stocks
	}
	return nil
}

func (x *GetMultipleStocksResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetMultipleStocksResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_market_proto protoreflect.FileDescriptor

const file_market_proto_rawDesc = "" +
	"\n" +
	"\fmarket.proto\x12\x06market\".\n" +
	"\x14GetStockPriceRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\xce\x01\n" +
	"\x15GetStockPriceResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rcurrent_price\x18\x03 \x01(\x01R\fcurrentPrice\x12%\n" +
	"\x0echange_percent\x18\x04 \x01(\x01R\rchangePercent\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"4\n" +
	"\x18GetMultipleStocksRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"\x91\x01\n" +
	"\x19GetMultipleStocksResponse\x125\n" +
	"\x06stocks\x18\x01 \x03(\v2\x1d.market.GetStockPriceResponseR\x06stocks\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2\xbb\x01\n" +
	"\x11MarketDataService\x12L\n" +
	"\rGetStockPrice\x12\x1c.market.GetStockPriceRequest\x1a\x1d.market.GetStockPriceResponse\x12X\n" +
	"\x11GetMultipleStocks\x12 .market.GetMultipleStocksRequest\x1a!.market.GetMultipleStocksResponseB;Z9github.com/FUNfarik/finance_microservices/proto/go/marketb\x06proto3"

var (
	file_market_proto_rawDescOnce sync.Once
	file_market_proto_rawDescData []byte
)

func file_market_proto_rawDescGZIP() []byte {
	file_market_proto_rawDescOnce.Do(func() {
		file_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)))
	})
	return file_market_proto_rawDescData
}

var file_market_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_market_proto_goTypes = []any{
	(*GetStockPriceRequest)(nil),      // 0: market.GetStockPriceRequest
	(*GetStockPriceResponse)(nil),     // 1: market.GetStockPriceResponse
	(*GetMultipleStocksRequest)(nil),  // 2: market.GetMultipleStocksRequest
	(*GetMultipleStocksResponse)(nil), // 3: market.GetMultipleStocksResponse
}
var file_market_proto_depIdxs = []int32{
	1, // 0: market.GetMultipleStocksResponse.stocks:type_name -> market.GetStockPriceResponse
	0, // 1: market.MarketDataService.GetStockPrice:input_type -> market.GetStockPriceRequest
	2, // 2: market.MarketDataService.GetMultipleStocks:input_type -> market.GetMultipleStocksRequest
	1, // 3: market.MarketDataService.GetStockPrice:output_type -> market.GetStockPriceResponse
	3, // 4: market.MarketDataService.GetMultipleStocks:output_type -> market.GetMultipleStocksResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_market_proto_init() }
func file_market_proto_init() {
	if File_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_proto_rawDesc), len(file_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_proto_goTypes,
		DependencyIndexes: file_market_proto_depIdxs,
		MessageInfos:      file_market_proto_msgTypes,
	}.Build()
	File_market_proto = out.File
	file_market_proto_goTypes = nil
	file_market_proto_depIdxs = nil
}
